### ISSUE TITLE
`volume` and `title` arguments on Client.upload_session should be optional

### ISSUE THREAD

**Issue by lukesaltweather** [AbstractUmbra/Hondana#25]
The API doesn't require these, as chapters not having titles or volumes is a common occurance (think for example web toons. There's also an issue that if you specify a volume, and every other language doesn't bother to, your translations are all cobbled up on the last page, since "No volume" chapters all come first. Real annoying).

However the upload_session enforces you to specify them.
It is possible to pass an empty string for title, but the regex for volume denies empty strings.
On this note, a chapter may also have no scanlation groups, so it being optional could also make sense, but this one I'm fine with.

That said, I'm having some issues with uploading in general, but I'll file a separate issue for this once I double checked my stuff.

Also fyi, since you mention in your readme that you're not able to test uploads, there is a test manga here:
https://mangadex.org/title/f9c33607-9180-4ba6-b85c-e4b5faee7192/official-test-manga
where you're allowed to just upload junk to.

**Comment by AbstractUmbra** [comment]
Hey, thanks for the heads up.

I'll get to work on fixing this for you, it's real simple with the current state of the code base. I'll also set up a local-only test bench for uploading now that I know about the test manga!

**Comment by AbstractUmbra** [comment]
I have now located another bug whilst testing, so perhaps this is related to the issue you were having!

The documentation for [committing chapters](https://api.mangadex.org/docs.html#operation/commit-upload-session) says it responds with a general `GetChapterResponse`, so `{"id": ..., "type": "chapter", ...}`

However in my testing we are actually getting a `GetSingleChapterResponse`, which is `{"result": "ok", "type": "entity", "data": GetChapterResponse}`.

I will now amend this.

**Comment by AbstractUmbra** [comment]
Fixed in 12d1cf4f97913204000ebfb5b384ae5f3a061f47.

**Comment by lukesaltweather** [comment]
Thank you! And glad I could help a bit.

Yes, that was the issue I was having :)
Works now with your changes.
