### ISSUE TITLE
Putting in a title with "&" in the name when searching will break the library

### ISSUE THREAD

**Issue by PythonCoderAS** [AbstractUmbra/Hondana#30]
### Summary

Searching for a manga with a title containing a "&" breaks it

### Reproduction Steps

I searched for a title with an & in it.

### Minimal Reproducible Code

```python
await client.manga_list(title="Ishida & Asakura")
```

### Expected Results

Search to return results

### Actual Results

```
---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
Cell In [32], line 1
----> 1 await main()

Cell In [7], line 4, in main()
      2 for row in tqdm.tqdm(data):
      3     if len(row) == 3 and len(row[2] or '') > 0:
----> 4         await search_one(row)

Cell In [31], line 4, in search_one(row)
      2 mal_id = row[2]
      3 title = row[1]
----> 4 possible_results = await client.manga_list(title=title)
      5 for result in possible_results.manga:
      6     result.links = result.links or {}

File ~/.local/share/virtualenvs/md-wikidata-resolve-crOtAD28/lib/python3.10/site-packages/hondana/client.py:682, in Client.manga_list(self, limit, offset, title, authors, artists, year, included_tags, excluded_tags, status, original_language, excluded_original_language, available_translated_language, publication_demographic, ids, content_rating, created_at_since, updated_at_since, order, includes, has_available_chapters, group)
    680 manga = []
    681 while True:
--> 682     data = await self._http._manga_list(
    683         limit=inner_limit,
    684         offset=offset,
    685         title=title,
    686         authors=authors,
    687         artists=artists,
    688         year=year,
    689         included_tags=included_tags,
    690         excluded_tags=excluded_tags,
    691         status=status,
    692         original_language=original_language,
    693         excluded_original_language=excluded_original_language,
    694         available_translated_language=available_translated_language,
    695         publication_demographic=publication_demographic,
    696         ids=ids,
    697         content_rating=content_rating,
    698         created_at_since=created_at_since,
    699         updated_at_since=updated_at_since,
    700         order=order,
    701         includes=includes,
    702         has_available_chapters=has_available_chapters,
    703         group=group,
    704     )
    706     manga.extend([Manga(self._http, item) for item in data["data"]])
    708     offset += inner_limit

File ~/.local/share/virtualenvs/md-wikidata-resolve-crOtAD28/lib/python3.10/site-packages/hondana/http.py:491, in HTTPClient.request(self, route, **kwargs)
    489 assert isinstance(data, dict)
    490 if response.status == 400:
--> 491     raise BadRequest(response, errors=data["errors"])
    492 elif response.status == 401:
    493     raise Unauthorized(response, errors=data["errors"])

BadRequest: HTTP Status: 400 and response id: 86815b85-8bed-456b-8870-3cece686fa48 :: Error validating : The property Asakura is not defined and the definition does not allow additional properties
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have included debug logging (with my latest token remove), if applicable.

**Comment by AbstractUmbra** [comment]
This one is actually really interesting.

I have tested a few methods to try and correct this, including url encoding the title specifically.

The outcomes are:-

<https://api.mangadex.org/manga?limit=100&offset=0&title=Ishida%20&%20Asakura>
will HTTP 400, due to the `&` as the API is interpreting this as a property/query parameter (which is expected.

However <https://api.mangadex.org/manga?limit=100&offset=0&title=Ishida+%26+Asakura> has the `&` url encoded, which returns no results as this searches for those characters literally, no url decoding takes place.

If we use something like `urllib.parse.quote`, then we get:
<https://api.mangadex.org/manga?limit=100&offset=0&title=Ishida%20%26%20Asakura>
Which then returns no results as the `&` does not get decoded again.

Another curiosity... searching in the website's UI for this manga title also doesn't work. This might be something I need to raise to them directly.

**Comment by PythonCoderAS** [comment]
> Another curiosity... searching in the website's UI for this manga title also doesn't work. This might be something I need to raise to them directly.

I think this manga might just not exist. The data I'm using might use alternate spellings or it might be for something not on MD.

**Comment by PythonCoderAS** [comment]
Ishida to Asakura is the name according to MAL, and that still doesn't exist.

**Comment by PythonCoderAS** [comment]
It does work with "Hana & Hina After School", which is an actual manga, although none of the variations on MD have the "&" in the alt titles.
